// <auto-generated />
using System;
using BlogProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlogProject.Migrations
{
    [DbContext(typeof(BlogContext))]
    partial class BlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlogProject.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "/img/dreaming.jpg",
                            Name = "Dream Log"
                        },
                        new
                        {
                            Id = 2,
                            Image = "/img/meditate.jpg",
                            Name = "Meditation"
                        },
                        new
                        {
                            Id = 3,
                            Image = "/img/yoga.jpg",
                            Name = "Yoga"
                        });
                });

            modelBuilder.Entity("BlogProject.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Josh",
                            BlogId = 1,
                            Body = "There was a duck. It was weird.",
                            PublishDate = new DateTime(2020, 3, 1, 17, 40, 54, 223, DateTimeKind.Local).AddTicks(1116),
                            Title = "That one time with the duck"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Johnny",
                            BlogId = 2,
                            Body = "I recommend amethyst for your salt baths to add positive energy to your relaxation experience.",
                            PublishDate = new DateTime(2020, 3, 1, 17, 40, 54, 228, DateTimeKind.Local).AddTicks(7486),
                            Title = "My Collection of Crystals"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Juniper",
                            BlogId = 3,
                            Body = "Come to my yoga classes on wednesdays at 3 pm!",
                            PublishDate = new DateTime(2020, 3, 1, 17, 40, 54, 228, DateTimeKind.Local).AddTicks(7557),
                            Title = "Want to step into the world of yoga?"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Ben",
                            BlogId = 1,
                            Body = "All my life, I had been terrified of flying. The concept of getting into a plane and traveling at high speeds for multiple hours made me feel sick to my stomach. But last night, I had a dream that I floated up into the clouds above the city. The buildings and roads looked beautiful from above. It was initially gut-wrenching, but the sensation of floating has convinced me that I need to see what the world looks like from the window of an airplane. I have a flight booked to New York City tomorrow.",
                            PublishDate = new DateTime(2020, 3, 1, 17, 40, 54, 228, DateTimeKind.Local).AddTicks(7565),
                            Title = "Flying"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Ben",
                            BlogId = 2,
                            Body = "I found a great resource online explaining exactly what meditation is and how it can help you in your everyday lives. You can check it out at this link here: https://mindworks.org/blog/meditation-definition/",
                            PublishDate = new DateTime(2020, 3, 1, 17, 40, 54, 228, DateTimeKind.Local).AddTicks(7569),
                            Title = "What Is Meditation?"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Josh",
                            BlogId = 3,
                            Body = "I spent a half hour in the afternoon doing yoga in the zen room with some friends. It was hard at first because I'm horribly out of shape, but at the end of the session I felt refreshed and happy. I highly recommend getting into yoga if you haven't already.",
                            PublishDate = new DateTime(2020, 3, 1, 17, 40, 54, 228, DateTimeKind.Local).AddTicks(7572),
                            Title = "My experience with yoga at We Can Code IT"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Josh",
                            BlogId = 3,
                            Body = "test",
                            PublishDate = new DateTime(2020, 3, 1, 17, 40, 54, 228, DateTimeKind.Local).AddTicks(7578),
                            Title = "Test"
                        });
                });

            modelBuilder.Entity("BlogProject.Models.PostTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PostId = 2,
                            TagId = 1
                        },
                        new
                        {
                            Id = 2,
                            PostId = 5,
                            TagId = 1
                        },
                        new
                        {
                            Id = 3,
                            PostId = 1,
                            TagId = 2
                        },
                        new
                        {
                            Id = 4,
                            PostId = 4,
                            TagId = 2
                        },
                        new
                        {
                            Id = 5,
                            PostId = 5,
                            TagId = 3
                        },
                        new
                        {
                            Id = 6,
                            PostId = 6,
                            TagId = 3
                        },
                        new
                        {
                            Id = 7,
                            PostId = 2,
                            TagId = 4
                        },
                        new
                        {
                            Id = 8,
                            PostId = 3,
                            TagId = 4
                        },
                        new
                        {
                            Id = 9,
                            PostId = 6,
                            TagId = 4
                        });
                });

            modelBuilder.Entity("BlogProject.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "relaxing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "subconscious"
                        },
                        new
                        {
                            Id = 3,
                            Name = "mindful"
                        },
                        new
                        {
                            Id = 4,
                            Name = "zen"
                        });
                });

            modelBuilder.Entity("BlogProject.Models.Post", b =>
                {
                    b.HasOne("BlogProject.Models.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlogProject.Models.PostTag", b =>
                {
                    b.HasOne("BlogProject.Models.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogProject.Models.Tag", "Tag")
                        .WithMany("PostTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
